In [6]:
import numpy as np
import scipy as sp

In [5]:
np.random.random((3,3))

array([[0.93283029, 0.01999745, 0.99265579],
       [0.09923067, 0.64996851, 0.33663912],
       [0.20465201, 0.9908868 , 0.62723287]])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.concatenate([np.array([1,2,3]), np.array([4,5,6])],axis=0)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.array([[1,2,3],[1,2,3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [16]:
np.expand_dims(np.array([1,2,3]), axis=0)

array([[1, 2, 3]])

In [19]:
A = np.random.random((3,3))
print(A)
A * A

[[0.29869504 0.34681681 0.20423947]
 [0.3783177  0.27214622 0.32025522]
 [0.47507814 0.89485521 0.83340418]]


array([[0.08921872, 0.1202819 , 0.04171376],
       [0.14312428, 0.07406356, 0.1025634 ],
       [0.22569924, 0.80076585, 0.69456253]])

In [20]:
A @ A

array([[0.31745537, 0.3807421 , 0.34228924],
       [0.3681056 , 0.49185255, 0.43132569],
       [0.87637516, 1.15407263, 1.07817429]])

In [24]:
b = np.random.random((3,1))
b

array([[0.78841349],
       [0.06489978],
       [0.63088518]])

In [25]:
A @ b

array([[0.38685519],
       [0.51797727],
       [0.95841626]])

In [1]:
import timeit

In [33]:
timeit.timeit("A @ B", setup = "import numpy as np; A = np.random.random((3,3)); B = np.random.random((3,3))", number=1000000) / 1000000

1.4169110999791884e-06

In [2]:
import numba as nb

In [8]:
def matrix_product(mat_a, mat_b):
    """Returns the product of the matrices mat_a and mat_b."""
    m = mat_a.shape[0]
    n = mat_b.shape[1]

    assert(mat_a.shape[1] == mat_b.shape[0])

    ncol = mat_a.shape[1]

    mat_c = np.zeros((m, n), dtype=np.float64)

    for row_ind in range(m):
        for col_ind in range(n):
            for k in range(ncol):
                mat_c[row_ind, col_ind] += mat_a[row_ind, k] * mat_b[k, col_ind]

    return mat_c

In [18]:
@nb.njit(nb.float64[:,:](nb.float64[:,:], nb.float64[:,:]), cache=True)
def matrix_product_nb(mat_a, mat_b):
    """Returns the product of the matrices mat_a and mat_b."""
    m = mat_a.shape[0]
    n = mat_b.shape[1]

    # assert(mat_a.shape[1] == mat_b.shape[0])

    ncol = mat_a.shape[1]

    mat_c = np.zeros((m, n), dtype=np.float64)

    for row_ind in range(m):
        for col_ind in range(n):
            for k in range(ncol):
                mat_c[row_ind, col_ind] += mat_a[row_ind, k] * mat_b[k, col_ind]

    return mat_c

In [19]:
timeit.timeit("matrix_product(A,B)",setup="from __main__ import matrix_product; import numpy as np; A = np.random.random((3,3)); B = np.random.random((3,3))", number = 10000) / 10000

2.0129569998243822e-05

In [20]:
timeit.timeit("matrix_product_nb(A,B)",setup="from __main__ import matrix_product_nb; import numpy as np; A = np.random.random((3,3)); B = np.random.random((3,3))", number = 100000) / 100000

1.1595539998961613e-06